### PR TITLE
Update environment.yml

### PR DESCRIPTION
**Pull request by teemu-ruokolainen**

### CODE REVIEW

**Comment by bast** [comment]
Thanks! There are test failures and maybe that's good and the test needs to be updated.

**Comment by teemu-ruokolainen** [comment]
I'll check it.

**Comment by rkdarst** [comment]
(aside: requirements.txt should also be updated at the same time)

**Comment by bast** [comment]
Also please use a more descriptive commit message with a context/goal/aim :-)

**Pull request merged**
