### PR TITLE
Add nbdime to requirements

### PR DESCRIPTION
**Pull request by rkdarst**
- Should be tested on binder to see if it integrates to jupyterlab
- Closes: #22

### CODE REVIEW

**Comment by bast** [comment]
Can @wikfeldt or @johanhellsvik please test? If not, I can test also.

**Comment by rkdarst** [comment]
I am trying to build on binder, but the whole image build takes a very, very long time.  (so long, it may not even be practical to use?)

**Comment by rkdarst** [comment]
Actually, it just finished now.  It appears to work in jupyterlab (last two icons, right?):
image

**Comment by bast** [comment]
It would be great to test to also look at an actual diff whether it shows it nicely.

**Comment by johanhellsvik** [comment]
Looking at it now

**Review by johanhellsvik — APPROVED** [review]
Diff with nbdime is working on mybinder.

**Pull request merged**
